#!/bin/bash
GRADING_DIR=$HOME/grading
TMP_DIR=/tmp/p5-grading/
REQUIRED_FILES="bookPairs.py"
MAIN_CODE="bookPairs.py"

# usage
if [ $# -ne 1 ]
then
     echo "Usage: $0 project5.zip" 1>&2
     exit 1
fi

# make sure that the script runs on VM
if [ `whoami` != "cs143" ]; then
     echo "ERROR: You need to run this script within the container" 1>&2
     exit 1
fi

ZIP_FILE=$1

# clean any existing files
rm -rf ${TMP_DIR}

# create temporary directory used for grading
mkdir ${TMP_DIR}

# unzip the zip file
if [ ! -f ${ZIP_FILE} ]; then
    echo "ERROR: Cannot find $ZIP_FILE" 1>&2
    rm -rf ${TMP_DIR}
    exit 1
fi
unzip -q -d ${TMP_DIR} ${ZIP_FILE}
if [ "$?" -ne "0" ]; then
    echo "ERROR: Cannot unzip ${ZIP_FILE} to ${TMP_DIR}"
    rm -rf ${TMP_DIR}
    exit 1
fi

# change directory to the partc folder
cd ${TMP_DIR}

# check the existence of the required files
for FILE in ${REQUIRED_FILES}
do
    if [ ! -f ${FILE} ]; then
        echo "ERROR: Cannot find ${FILE} in the root folder of ${ZIP_FILE}" 1>&2
        rm -rf ${TMP_DIR}
        exit 1
    fi
done

# run the student code
echo "Executing your Spark code....." 1>&2
spark-submit ${MAIN_CODE}

# check if the expected output directory and files have been generated
if [ ! -d output ]; then
    echo "ERROR: Output directory "output" was not created by your Spark code" 1>&2
    rm -rf ${TMP_DIR}
    exit 1
fi
if [ ! -f 'output/part-00000' ]; then
    echo "ERROR: Cannot find the output file output/part-00000 after your code is run" 1>&2
    rm -rf ${TMP_DIR}
    exit 1
fi
head -5 output/part-????? 1>&2

# clean up
rm -rf ${TMP_DIR}

echo
echo "SUCCESS! We finished testing your zip file integrity." 1>&2
exit 0
